### PR TITLE
Fix a bug with setting the transaction done page promos

### PR DESCRIPTION
**Pull request by issyl0**
- It was reported that new done pages failed to save when adding the
  organ donation promo to them.

### CODE REVIEW

**Comment by benilovj** [comment]
Is it worth adding a test to cover the case that was broken?

**Comment by issyl0** [comment]
Interestingly, there's already a test for whether you can fill in the boxes and it saves: https://github.com/alphagov/publisher/blob/master/test/integration/completed_transactions_create_edit_test.rb#L69, but it hasn't ever failed else we'd have noticed sooner, so I don't know what went wrong there. I'll look into it.

**Comment by h-lame** [comment]
Looks like the test doesn't fail because that's checking the update action and I can't see that the update action uses the `permitted_params` (or does any strong parameters style work at all TBH - but that seems unlikely so I must not be tracing it through), whereas the create action does, but there's no similar test for promos on that.

**Comment by issyl0** [comment]
Right, I've added an explicit page refresh to the existing integration test (linked above) so that it does actually check that, once saved and the page refreshed, the selections are still there. The AJAX was never reloading the page, so the test was continually passing.

**Pull request merged**
