### PR TITLE
Use an index for sorting on the org content report.

### PR DESCRIPTION
**Pull request by elliotcm**
Optimization to bring down the request time for the `organisation-content.csv` report.

### CODE REVIEW

**Comment by elliotcm** [comment]
Will need to run `rake db:mongoid:create_indexes` when deploying.

**Comment by bradleywright** [comment]
@elliotcm see alphagov-deployment#808

**Comment by alext** [comment]
That's already in place for publisher - https://github.gds/gds/alphagov-deployment/blob/master/publisher/config/deploy.rb#L71

**Comment by elliotcm** [comment]
Bonza.  Thanks both.

**Pull request merged**
