### PR TITLE
[DO NOT MERGE] Upgrade Rails

### PR DESCRIPTION
**Pull request by binaryberry**
Still WIP as it needs a rebase on master, but all tests are passing locally. Needs the [govuk_content_models PR](https://github.com/alphagov/govuk_content_models/pull/436) to be merged, and the gem to be bumped, for tests to pass here.

https://trello.com/c/H3gARFuk/56-upgrade-publisher-to-rails-5

### CODE REVIEW

**Comment by issyl0** [comment]
Can we squash 7dd8899 and b063e36 together?

**Comment by sihugh** [comment]
We certainly can!

**Comment by issyl0** [comment]
There are the correct number of users now!

**Comment by issyl0** [comment]
Synk is unhappy - I think it's so far an unfixable Nokogiri gem issue.

**Comment by sihugh** [comment]
Yep, we can proceed even if Snyk's unhappy for this.  We have more upgrades to come 😱

**Pull request merged**
