### PR TITLE
Ensure that Services is loaded.

### PR DESCRIPTION
**Pull request by danielroseman**
Speculative fix for `NameError: uninitialized constant PublishingAPIUpdater::Services`

### CODE REVIEW

**Comment by bradwright** [comment]
@danielroseman shall we deploy this to Integration and see if it works?

**Comment by tijmenb** [comment]
I believe I solved it like this previously: 

https://github.com/alphagov/collections-publisher/pull/149

**Comment by danielroseman** [comment]
@tijmenb thanks, do you think that's the same issue though? Your PR there talks about an explicit circular dependency error message, we're just getting uninitialized constant.

**Comment by tijmenb** [comment]
I think so. I could be mistaken but I think the circular dependency error is actually a masked uninitialized constant error. At the time I thought it was caused because collections-publisher has a `/app/services` directory.

**Pull request merged**
