### PR TITLE
Retire programme format

### PR DESCRIPTION
**Pull request by emmabeynon**
The programme format is being retired.  The main work to deal with removing users' ability to create artefacts and editions for retired formats, and display an appropriate message about retired formats to users, happened here: https://github.com/alphagov/publisher/pull/586.  This PR bumps `govuk_content_models` to a version that recognises programmes as a retired format, and removes redundant code related to programmes.  

[Trello](https://trello.com/c/aonp9YbK/675-retire-programme-format-2)

### CODE REVIEW

**Comment by davidbasalla** [comment]
The Readme could be updated, as we did for the Video format

**Comment by davidbasalla** [comment]
I think the editions controller still refers to programmes -> https://github.com/alphagov/publisher/blob/2a31777418025cb71d7ce93a522a4b549585bbcb/app/controllers/editions_controller.rb#L263

**Comment by emmabeynon** [comment]
@davidbasalla I've removed those references to Programme and a few other redundant tests 👍

**Comment by davidbasalla** [comment]
Great! Looks good to merge!

**Pull request merged**
