### PR TITLE
Add publishing-api presenter for Guide editions

### PR DESCRIPTION
**Pull request by whoojemaflip**
Trello: https://trello.com/c/r2gA1lxN/640-migrate-guide-format-to-rendered

Paired with @emmabeynon

### CODE REVIEW

**Comment by davidbasalla** [comment]
Are you planning to have another PR for adding the format to `MIGRATED_EDITION_CLASSES` for updating the preview link?

**Comment by whoojemaflip** [comment]
@davidbasalla I think I must have pushed that commit at exactly the same time as your comment.

**Comment by davidbasalla** [comment]
You could add a test for the migrated format to https://github.com/alphagov/publisher/blob/master/test/unit/edition_test.rb#L81-L101

Looks good otherwise! There might be a small edge case where a user could add a new part but not fill in the title. Publisher does not seem to validate the presence of `title` and lets you save the edition, but presumably pushing to the publishing api will fail because it expects a string (actually that depends if it gets `nil` or an empty string I suppose). Anyway, I had a look in Publisher in integration and couldn't find any published Guides where the title was `nil`, so it's probably nothing to worry about.

**Comment by whoojemaflip** [comment]
Yep, always getting caught out by the nil values. @davidbasalla fixed

**Comment by davidbasalla** [comment]
🎉 👍

**Pull request merged**
