### PR TITLE
Upgrade Bootstrap to 3.3.2 and manage analytics via admin gem

### PR DESCRIPTION
**Pull request by fofr**
* Upgrade Bootstrap to 3.3.2 (via bootstrap-sass 3.3.3)
  * Includes autoprefixer rails which is a new Bootstrap dependency
* Include Google analytics managed by gem https://github.com/alphagov/govuk_admin_template/pull/59
  * Remove existing snippet
  * Update analytics usage to match new API

https://github.com/alphagov/govuk_admin_template/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by bradleywright** [comment]
Should we roll a new release including alphagov/govuk_admin_template#60?

**Comment by fofr** [comment]
Yes, definitely.

**Comment by benilovj** [comment]
Closing while bumping to newer version of `govuk_admin_template` gem

**Comment by benilovj** [comment]
I've bumped `govuk_admin_template` to version 2.1.0, which picks up alphagov/govuk_admin_template#60 .

The rest LGTM :+1:

**Pull request merged**
